### ISSUE TITLE
New to linux, but desperately need the adblock for spotify.

### ISSUE THREAD

**Issue by riskirills66** [abba23/spotify-adblock#13]
The problem is, I just copy-paste all your command lines in the terminal, but none of them work. What am I supposed to do with this or that?
no clue at all.
could you make a friendly tutorial for a newbie?

**Comment by Greatest125** [comment]
When copying and pasting commands don't include the `$`.

So for example:

`git clone https://github.com/abba23/spotify-adblock.git`
instead of 
`$ git clone https://github.com/abba23/spotify-adblock.git`

Also, you need to install rust first:

`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

Welcome to the world of Linux! There is a lot to learn but it's a fun time!

**Comment by riskirills66** [comment]
ok, i'll try.
this looks simple, but i will go back here if i encounter another problem.
thanks

**Comment by abba23** [comment]
I'm sorry, but this is not the right place for general Linux support. Questions of that type are usually answerable by an internet search engine though. If you encounter a specific problem related to this project, you're welcome to create a new issue.

If you do create issues in the future, please include any relevant information about your system (e.g. your Linux distribution), what you did (e.g. the exact commands you ran) and what happened (e.g. the terminal output). It's incredibly hard to diagnose a problem if all you know is that *something doesn't work*.
