### ISSUE TITLE
Problem with spotifywm-git.

### ISSUE THREAD

**Issue by mactemporal** [abba23/spotify-adblock#133]
So, when trying to execute spotify-adblock with spotifywm-git, and by doing what's indicated in issue #44, i.e. :
`LD_PRELOAD="<path to>/spotify-adblock.so <path to>/spotifywm.so" spotify` which for me is :
`LD_PRELOAD="/usr/lib/spotify-adblock.so /usr/lib/spotifywm.so" spotify` it prints me the same error : 
`/bin/sh: symbol lookup error: /usr/lib/spotify-adblock.so: undefined symbol: cef_string_userfree_utf16_free`

Any ideas?
I'm on Arch Linux and using Bspwm. Thank you!

**Comment by mactemporal** [comment]
Fixed by doing : `Exec=env LD_PRELOAD="/usr/lib/spotify-adblock.so /usr/lib/spotifywm.so" /opt/spotify/spotify %U`
in a desktop file BUT not in `/usr/share/applications/` but in `/home/<user>/.local/share/applications/` 
WHY? -> I don't know and I don't want to think about it.
Spotify is then executed by a bash script in bspwrc.
Thank you for everything!

**Comment by jazz-it** [comment]
I also had this issue, so to prevent from opening another issue, I will add my comment here. Before my recent update, everything worked as per the line below:

```
env LD_PRELOAD="/usr/lib/spotify-adblock.so" spotify %U
```

Now, after the major update, it throws the following error: `symbol lookup error: /usr/lib/spotify-adblock.so: undefined symbol: cef_string_userfree_utf16_free`

Since I don't have a file `/usr/lib/spotifywm.so`, I just modified `spotify` to `/opt/spotify/spotify` and now it works. @abba23 Any ideas why and should this be a permanent workaround?

```
env LD_PRELOAD="/usr/lib/spotify-adblock.so" /opt/spotify/spotify %U
```
