### ISSUE TITLE
Duplicate icons in Ubuntu 20.04 dock

### ISSUE THREAD

**Issue by karelo911** [abba23/spotify-adblock#27]
There is one little annoyance I'm facing at the moment, and that is when I pin "Spotify (adblock)" as a favorite in the Ubuntu dock, it seems to open to a new icon instead of the pinned one. I tried other suggestions online which is to identify the StartupWMClass using xprop and modify the custom .desktop file, which I later found out to be appended already. I tried renaming to "Spotify" and "spotify" for both .desktop files (the ones in the /usr/share and ./local/share), still with the same results. I use a custom icon pack btw.

![Screenshot from 2021-07-16 14-52-37](https://user-images.githubusercontent.com/40468059/125905113-7b51069f-63fa-4412-ad98-9b738ea213b2.png)

Nonetheless, everything else is working fine for me so far, thanks for making this project possible!

**Comment by abba23** [comment]
Did you reboot after making those changes to make sure the modified desktop files were actually loaded? You should also usually not modify the files in `/usr/share/applications` and instead just override them in `~/.local/share/applications`.

Other than that, I can't really help you with this as it seems like more of a desktop environment specific problem, rather than an issue with the adblocker. The desktop file in the readme is just meant as an example that might need to be adapted anyway.

**Comment by karelo911** [comment]
I did delete my file in `.local`, then modified the desktop file in `/usr/share/applications`, and it worked like a charm! I haven't encountered any issues so far (I made a compressed backup of the original desktop file just in case).
