### ISSUE TITLE
Seems like it stop working some weeks ago

### ISSUE THREAD

**Issue by tejonaco** [abba23/spotify-adblock#45]
It's like spotify changed something and this stop working, not only this repo, I had other mod for windows and it stopped working again.

**Comment by g4gg433** [comment]
Same here. Reinstalled it multiple times on a clean flatpak install and it just doesn't do anything anymore. #12 still occurs (ie the empty box is still there) but the playback ads get through.

Though it used to work a couple days before (but the flatpak only got updated very recently) so it is probably the same issue.

**Comment by Bobu5** [comment]
newbie here, it also doesnt work for me

**Comment by abba23** [comment]
I'll need need a little more information than just the fact that it doesn't work to have a chance at helping.

What's your Spotify version? Are you all using the Flatpak version? Please also provide the terminal output, in particular from when ads are starting to play.

**Comment by Bobu5** [comment]
> I'll need need a little more information than just the fact that it doesn't work to have a chance at helping.
> 
> What's your Spotify version? Are you all using the Flatpak version? Please also provide the terminal output, in particular from when ads are starting to play.

hi abba23, thx for the reply

no im not using flatpak, im installing via their PPA (and then apt install) , i just installed it this morning so yeah im pretty sure its the latest version, im sorry i cant provide the version of my spotify as of rn since im not home, but imma vnc or ssh then check the spotify later

**Comment by g4gg433** [comment]
Just tried it out after running flatpak update: Spotify version 1.1.55.498.gf9a83c60

When getting an ad I get no terminal output at all (should there be something anyway?). They probably introduced another domain that simply isn't on the blacklist.

**Comment by abba23** [comment]
@Bobu5

>installing via their PPA (and then apt install)

That should be fine then.

>i just checked the version, Spotify version 1.1.67.586.gbb5ef64e

I've got the same version and it's working for me. Can't tell you much more without seeing that terminal output.

---

@g4gg433
>When getting an ad I get no terminal output at all (should there be something anyway?).

There should be a line beginning with `[+]` for every allowed domain/URL and `[-]` for every blocked one. If those don't appear for you, then the adblocker isn't loaded. If so, do you see any errors in the terminal output that might be related?

>They probably introduced another domain that simply isn't on the blacklist.

That's why this works primarily through an allowlist. Unless they're using an URL with a domain already on that list, it's not a problem. Also, as mentioned above, it's still working for me, so it's at least unlikely that this is the reason.

**Comment by Bobu5** [comment]
> @Bobu5
> 
> > installing via their PPA (and then apt install)
> 
> That should be fine then.
> 
> > i just checked the version, Spotify version 1.1.67.586.gbb5ef64e
> 
> I've got the same version and it's working for me. Can't tell you much more without seeing that terminal output.

thanks for the reply again abba23 , first of all im sorry i forgot to put the log file, imma try to log it now and run it for a few hour, and report back if the ad poped up again, but what im sure is the banner is here
![image](https://user-images.githubusercontent.com/87025837/133947954-5f49df8b-f0c1-403a-8b27-341010670325.png)

oh and yes i've done what u have said , [the make and then sudo make install thing] but im not sure if ive done it properly since im a newbie on linux

and once again, thanks for your reply and your works

**Comment by Bobu5** [comment]
finally got spotify to play the ad, imma put the log on pastebin since i think its too large for it to be putted here

https://pastebin.com/GggzpQ49

**Comment by abba23** [comment]
Looks like you launched Spotify with the `--show-console` flag, which is not necessary. It also doesn't seem like the adblocker is loaded. Did you launch Spotify exactly as described in the readme (i.e. `LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify`)? Were there any error messages before that part of the log?

**Comment by Bobu5** [comment]
> Looks like you launched Spotify with the `--show-console` flag, which is not necessary. It also doesn't seem like the adblocker is loaded. Did you launch Spotify exactly as described in the readme (i.e. `LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify`)? Were there any error messages before that part of the log?

well, damn did i just wasted someone's time again? , so sorry i didnt realized that, and yeah running that command seems to fixed it (atleast the banner) , if u dont hear from me again in this ticket, its probably already resolved the 

i thought it was some problem with my driver or smthgn that the --log-file didnt work, so i do --show-console , and yeah 

i think i just wasted someone's time , so sorry

**Comment by g4gg433** [comment]
>There should be a line beginning with [+] for every allowed domain/URL and [-] for every blocked one. If those don't appear for you, then the adblocker isn't loaded. If so, do you see any errors in the terminal output that might be related?

Turns out I didn't get the banners because of my DNS server blocking a lot of domains already.

**Comment by TheKingofChicken** [comment]
I have the same issue, when running from the command line, the adds correctly disapear. When using the .desktop file, which contains the same command, the ads seem to load. Which really makes it seem like it's an user error on my part. Does anyone know what command is used to load ads? I thought it was getaddrinfo before noticing the r.


Currently using linux Mint 20.0

**Comment by TheKingofChicken** [comment]
if it can help anyone, this is the .desktop file I'm using.

[Desktop Entry]
Type=Application
Name=Spotify
GenericName=Music Player
Icon=spotify-client
Exec=env LD_Preload=/usr/local/lib/spotify-adblock.so spotify
Terminal=false
MimeType=x-scheme-handler/spotify;
Categories=Audio;Music;Player;AudioVideo;
StartupWMClass=spotify

**Comment by abba23** [comment]
I don't think an issue that essentially amounts to "It's not working" is very useful. There are already multipe people here with problems that are likely completely unrelated. I'll close this until @tejonaco can provide some details.

---

@TheKingofChicken 
>LD_Preload

Environment variable names are case-sensitive. The correct name is `LD_PRELOAD`.

**Comment by tejonaco** [comment]
Hi, Inwill post the requested output when I can use my pc, told that this was working for me for months, I had archlinuxcn compiled spotify I think, I will probide more details soon, thanks!
